import {
  Zap,
  ChevronDown,
  ChevronUp,
  ChevronsUpDown,
  ChevronRight,
  ChevronLeft,
  ArrowRight,
  ArrowLeft,
  ArrowDown,
  ArrowUp,
  Download,
  Link,
  MapPin,
  LineChart,
  BarChart,
  Bell,
  DollarSign,
  Bitcoin,
  Briefcase,
  AlertTriangle,
  Settings,
  TrendingUp,
  TrendingDown,
  Calendar,
  Shield,
  Activity,
  Eye,
} from "lucide-react"

export const Icons = {
  zap: Zap,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  chevronsUpDown: ChevronsUpDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  download: Download,
  link: Link,
  mapPin: MapPin,
  lineChart: LineChart,
  barChart: BarChart,
  bell: Bell,
  dollarSign: DollarSign,
  bitcoin: Bitcoin,
  briefcase: Briefcase,
  alertTriangle: AlertTriangle,
  settings: Settings,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  calendar: Calendar,
  shield: Shield,
  activity: Activity,
  eye: Eye,
}
